conf/example_config.sql, public/common/control-messages.component.ts, public/home/home.html, public/home/home.ts, public/home/influxmeascfg.component.ts, public/home/influxmeascfg.service.ts, public/home/influxmeaseditor.css, public/home/influxmeaseditor.html, public/home/influxservercfg.component.ts, public/home/influxservereditor.css, public/home/influxservereditor.html, public/home/measfiltercfg.component.ts, public/home/measfiltercfg.service.ts, public/home/measfiltereditor.css, public/home/measfiltereditor.html, public/home/measgroupcfg.component.ts, public/home/measgroupcfg.service.ts, public/home/measgroupeditor.css, public/home/measgroupeditor.html, public/home/snmpdevicecfg.component.ts, public/home/snmpdevicecfg.service.ts, public/home/snmpdeviceeditor.css, public/home/snmpdeviceeditor.html, public/home/snmpmetriccfg.component.ts, public/home/snmpmetriceditor.css, public/home/snmpmetriceditor.html, public/main.module.ts, public/sass/styles/styles.css
UI Form:
- Refactor styles on forms
- Added multiselect based on ng-bootstrap collection
- Added tooltip elements based on ng-bootstrap collection
- Fix some input values
- Removed unnecessary inputs
- Ordered panel according to the steps to add a SNMP Device on SQL
=> Refactor UI Form

CHANGELOG.md, package.json, pkg/influx.go, pkg/influxmeasurement.go, pkg/main.go, pkg/snmpdevice.go
- Snmpdev measurement refactor.
- snmp fixes for snmpv1
- Improved code coments.
- bulkwalkall  to  bulkwalk to prevent out of order failures (https://github.com/toni-moreno/snmpcollector/issues/11)
=> snmpdevice  and influxmeasurement objects refactor and snmp fixes 

conf/snmpcollector_init
=> Init.d script

pkg/webserver.go, public/common/validation.service.ts, public/influxmeas/influxmeascfg.component.ts, public/influxmeas/influxmeascfg.service.ts, public/influxmeas/influxmeaseditor.html, public/influxserver/influxservercfg.component.ts, public/influxserver/influxservercfg.service.ts, public/main.module.ts, public/measfilter/measfiltercfg.component.ts, public/measfilter/measfiltercfg.service.ts, public/measfilter/measfiltereditor.html, public/measgroup/measgroupcfg.component.ts, public/measgroup/measgroupcfg.service.ts, public/snmpdevice/snmpdevicecfg.component.ts, public/snmpdevice/snmpdevicecfg.service.ts, public/snmpdevice/snmpdeviceeditor.html, public/snmpmetric/snmpmetriccfg.component.ts, public/snmpmetric/snmpmetriccfg.service.ts
· Readded macaron bindings on snmpdevices
· Add validators on all form fields
· Bound custom Validators to ngmodule
· Fixed some form fields:
- Fixed refresh of multiselects on updating the group
- Fixed treatment of booleans, now they are updated correctly
=> Fix forms, multiselect refreshing and boolean treatment

public/common/multiselect-dropdown.ts, public/common/ng-table/components/table/ng-table.component.ts, public/common/validation.service.ts, public/home/home.html, public/influxmeas/influxmeascfg.component.ts, public/influxmeas/influxmeaseditor.html, public/influxserver/influxservercfg.component.ts, public/influxserver/influxservereditor.html, public/measfilter/measfiltercfg.component.ts, public/measfilter/measfiltereditor.html, public/measgroup/measgroupcfg.component.ts, public/measgroup/measgroupeditor.html, public/snmpdevice/snmpdevicecfg.component.ts, public/snmpdevice/snmpdeviceeditor.html, public/snmpmetric/snmpmetriccfg.component.ts, public/snmpmetric/snmpmetriceditor.html
- Added search button and change check items on multiselect
- Fix issue #33 and related fields with incorrect names. Now all fields of devices are displayed
- Replaced booleans with glyphicons on tables
- Fix issue #30 - checking nulls on reset
- Add snmpcollector instance name on footer
=> UI Fix some issues (#30, #33)

public/main.module.ts, public/snmpdevice/snmpdevicecfg.component.ts, public/snmpdevice/snmpdevicecfg.service.ts, public/snmpdevice/snmpdeviceeditor.html
Added test connection button using alerts from ng2-bootstrap module.
Pings the device and gets the result before adding or editing devices
=> added test connection button

public/home/home.html, public/home/home.ts, public/main.module.ts, public/runtime/runtime.component.ts, public/runtime/runtime.service.ts, public/runtime/runtimeeditor.css, public/runtime/runtimeview.html
Added Runtime view providing options to control devices and check their connectivity
=> UI Add Runtime view

pkg/model.go, public/common/generic-modal.ts, public/influxmeas/influxmeascfg.component.ts, public/influxmeas/influxmeascfg.service.ts, public/influxmeas/influxmeaseditor.html, public/influxserver/influxservercfg.component.ts, public/influxserver/influxservercfg.service.ts, public/influxserver/influxservereditor.html, public/measfilter/measfiltercfg.component.ts, public/measfilter/measfiltercfg.service.ts, public/measfilter/measfiltereditor.html, public/measgroup/measgroupcfg.component.ts, public/measgroup/measgroupcfg.service.ts, public/measgroup/measgroupeditor.html, public/runtime/runtimeview.html, public/snmpdevice/snmpdevicecfg.component.ts, public/snmpdevice/snmpdevicecfg.service.ts, public/snmpdevice/snmpdeviceeditor.html, public/snmpmetric/snmpmetriccfg.component.ts, public/snmpmetric/snmpmetriccfg.service.ts, public/snmpmetric/snmpmetriceditor.html
Change simple alert command to modal dialog component:
=> Enhanced custom_modal component for delete components

public/app/app.routes.ts, public/common/headers.ts, public/common/httpAPI.ts, public/home/home.ts, public/influxmeas/influxmeascfg.component.ts, public/influxmeas/influxmeascfg.service.ts, public/influxserver/influxservercfg.service.ts, public/login/login.ts, public/main.module.ts, public/measfilter/measfiltercfg.service.ts, public/measgroup/measgroupcfg.service.ts, public/runtime/runtime.service.ts, public/snmpdevice/snmpdevicecfg.service.ts, public/snmpmetric/snmpmetriccfg.service.ts
Added HTTP Wrapper to control all http request from components.
Other fixes
- remove reset form when adding a measurement
=> Add UI HTTP Wrapper to control request from components

public/common/spinner.ts, public/common/test-connection-modal.ts, public/css/spinner.css, public/main.module.ts, public/snmpdevice/snmpdevicecfg.component.ts, public/snmpdevice/snmpdevicecfg.service.ts, public/snmpdevice/snmpdeviceeditor.html
Added new modal to let the user make direct queries with data from edit/add devices form:
- Ping the device retrieving sysInfo
- Allows to select existing metrics and make queries with assigned OID
- Allows input custom OID
The result is displayed on a table and gives you the PDU info: OID, type and value
=> Ui add console connection

public/common/test-connection-modal.ts
Added new selectors: Indexed Measurement and OID cond Filters
Cleaned up the interface
Added expand/collapse button on query results
Added history pannel to let the user send again the last queries faster
=> Enhanced console connection modal component

public/runtime/runtime.component.ts, public/runtime/runtime.service.ts, public/runtime/runtimeview.html
Added new button and selector to change the log level of the devices on runtime
=> Add button to set log level of the devices on runtime

src/home/home.html, src/influxmeas/influxmeaseditor.html, src/influxserver/influxservereditor.html, src/login/login.html, src/measfilter/measfiltereditor.html, src/measgroup/measgroupeditor.html, src/runtime/runtimeview.html, src/snmpdevice/snmpdeviceeditor.html, src/snmpmetric/snmpmetriceditor.html
Indented all webUI html files
Minor fix on tooltips after upgrading to last version of ng2-bootstrap
=> Indent all webUI html files

src/css/simple-sidebar.css, src/home/home.html, src/home/home.ts
- The instance name is under brand name, helping the user to which config is modifying.
- Added actived class when menu is selected
=> Enhanced webUI menu, cleaned redundant code and fix indented

src/common/test-connection-modal.ts, src/css/simple-sidebar.css, src/home/home.html
Also fixed swapped icons on expand/collapse query view
=> fix webUI testconnection modal css introduced in wrapper enhance

src/common/ng-table/components/ng-table-module.ts, src/common/ng-table/components/table/ng-table-keypipe.ts, src/common/ng-table/components/table/ng-table.component.ts, src/runtime/runtime.component.ts, src/runtime/runtimeeditor.css, src/runtime/runtimeview.html
Enhanced runtime using ng2-table and improved ngtable.
**Runtime**
- Used panel groups to have better order of different sections of runtime.
- Changed "Edit" panel to "Runtime Options" panel
- Improved message returned to the user when info on runtime (sysinfo/metricinfo) couldn't be retrieved for some reasons.
- Expanded metric using ng2-table:
- Added tooltip on each cell with full runtime-metric info
**Ng-table on components**
- Added tooltip description on different buttons
- Added tooltip showing the description of each row
=> Ui enhance runtime ngtable

src/runtime/runtime.component.ts, src/runtime/runtimeeditor.css, src/runtime/runtimeview.html
- Added auto refresh on runtime based on Device ```freq``` parameter
- Added snmp extra tags info
- Added snmp statistics
- Added measurement filter descrpition  asociated with selected measurement on metrics info
- Added scrollbar X on tables
- Bootstrapped elemtens and make some visuals changes according to improve visualization
=> Added auto refresh and other features on runtime info

src/common/ng-table/components/table/ng-table.component.ts, src/influxmeas/influxmeascfg.component.ts, src/influxmeas/influxmeaseditor.html, src/main.module.ts
Added metric report case on measurements to indicate if metric should be reported, not reported or only reported when the value is zero.
=> Added new metric reports type on measurement definition

src/common/multiselect-dropdown.ts, src/common/test-connection-modal.ts, src/influxserver/influxservereditor.html, src/measfilter/measfiltercfg.component.ts, src/measfilter/measfiltereditor.html, src/measgroup/measgroupcfg.component.ts, src/measgroup/measgroupeditor.html, src/snmpdevice/snmpdevicecfg.component.ts, src/snmpdevice/snmpdeviceeditor.html, src/snmpmetric/snmpmetriceditor.html
This PR to fixes:
- Fixed the case when editing a component with multiselect the already selected fields are not loaded correctly so the component was treating them as null selected.
- Fixed Filter forms, added conditional visibility when selecting type of filter
- Changed invocation of component params on test connection modal. Now the request is done when the user clicks on show modal.
- Changed tooltipplacement to placement on all html file components.
- Changed indention according to the entire project
=> UI Fix multiselect load fields when editing mode and other minor issues

src/css/component-styles.css, src/influxmeas/influxmeascfg.component.ts, src/influxmeas/influxmeaseditor.html, src/influxserver/influxservercfg.component.ts, src/influxserver/influxservereditor.html, src/measfilter/measfiltercfg.component.ts, src/measfilter/measfiltereditor.html, src/measgroup/measgroupcfg.component.ts, src/measgroup/measgroupeditor.html, src/snmpdevice/snmpdevicecfg.component.ts, src/snmpdevice/snmpdeviceeditor.html, src/snmpmetric/snmpmetriccfg.component.ts, src/snmpmetric/snmpmetriceditor.html
=> UI Add button to remove filter, add selector to set items per page

pkg/webui/webserver.go, proxy.conf.json, src/home/home.ts, src/influxmeas/influxmeascfg.service.ts, src/influxserver/influxservercfg.service.ts, src/measfilter/measfiltercfg.service.ts, src/measgroup/measgroupcfg.service.ts, src/runtime/runtime.service.ts, src/snmpdevice/snmpdevicecfg.service.ts, src/snmpmetric/snmpmetriccfg.service.ts
UI API refactor according to #53
=> UI API Refactor

src/common/generic-modal.ts
Set correct icons and style on view measurement modal after adding the report types field on metrics
=> UI Set correct icons and styles on view measurement modal

src/common/multiselect-dropdown.ts
Add single option on multiselect dropdown.
It must be defined on the settings of the multiselect:
```
private mySettings: IMultiSelectSettings = {
singleSelect: true,
};
```
And load them on html call:
```
<ss-multiselect-dropdown 
...  
[settings]="mySettings">
</ss-multiselect-dropdown>
```
=> UI Add single option on multiselect dropdown

src/common/ng-table/components/table/ng-table.component.ts, src/customfilter/customfilter.service.ts, src/customfilter/customfiltercfg.component.ts, src/customfilter/customfiltereditor.html, src/customfilter/filter-modal-styles.css, src/customfilter/test-filter-modal.ts, src/customfilter/testingfilter.html, src/home/home.html, src/home/home.ts, src/main.module.ts, src/measfilter/measfiltereditor.html, src/snmpdevice/snmpdevicecfg.component.ts, src/snmpdevice/snmpdeviceeditor.html
- Add custom filter component as a new type of Measurement Filter.
- Added editor modal to let the user create a custom filter with directly the results from a query.
- Added button on device add/edit to start creating a custom filter directly on its own configuration.
- Enhanced Measurement Filter edition using single select setting of multiselect
=> UI Add custom filter component as a new type of Measurement Filters

src/common/validation.service.ts, src/customfilter/testingfilter.html, src/influxmeas/influxmeascfg.component.ts, src/measfilter/measfiltercfg.component.ts, src/measgroup/measgroupcfg.component.ts, src/runtime/runtimeview.html, src/snmpdevice/snmpdevicecfg.component.ts, src/snmpmetric/snmpmetriccfg.component.ts
Minor fixes on components and fix empty fields on the multiselect options
=> UI Minor fixes on components

src/customfilter/customfiltercfg.component.ts, src/customfilter/customfiltereditor.html, src/influxmeas/influxmeascfg.component.ts, src/influxmeas/influxmeaseditor.html, src/influxserver/influxservercfg.component.ts, src/influxserver/influxservereditor.html, src/measfilter/measfiltercfg.component.ts, src/measfilter/measfiltereditor.html, src/measgroup/measgroupcfg.component.ts, src/measgroup/measgroupeditor.html, src/oidcondition/oidconditioncfg.component.ts, src/oidcondition/oidconditioneditor.html, src/runtime/runtime.component.ts, src/runtime/runtimeview.html, src/snmpdevice/snmpdevicecfg.component.ts, src/snmpdevice/snmpdeviceeditor.html, src/snmpmetric/snmpmetriccfg.component.ts, src/snmpmetric/snmpmetriceditor.html
Seems it was an issue when the user was trying to filter or selecting items per page and the selected page was more than 1.
=> UI Fix table exception on filtering and selecting items per page if the selected page is more than 1

src/common/multiselect-dropdown.ts, src/influxserver/influxservereditor.html, src/measfilter/measfiltereditor.html, src/snmpdevice/snmpdevicecfg.component.ts, src/snmpdevice/snmpdeviceeditor.html
I think this finally fixes blank selector case on multiselect
Small fixes:
Added single select on missing components using multiselect
=> UI fixes blank cases on multiselect

src/common/generic-modal.ts
Now the items related on custom filter are shown on view modal:
=> UI Fixed show items from filter component when loading view modal

pkg/config/database.go, src/customfilter/customfilter.service.ts, src/influxmeas/influxmeascfg.service.ts, src/influxserver/influxservercfg.service.ts, src/measfilter/measfiltercfg.service.ts, src/measgroup/measgroupcfg.service.ts, src/oidcondition/oidconditioncfg.service.ts, src/snmpdevice/snmpdevicecfg.service.ts, src/snmpmetric/snmpmetriccfg.service.ts
Now the information given to the user shows the new Type Desc, so its easier to see what is affecting to
=> UI Added Type Description  when deleting some component

pkg/config/database.go, pkg/config/snmpmetriccfg.go
- Fix update functions on all components. It seems that update function behaivour is specified depending on what functions are attached. The proposed fixes the bug described at #140.
- Fix adding a Metric with selected datasource type COUNTERXX
=> UI Fix update function on all components, fix #140 

src/common/control-messages.component.ts, src/common/test-connection-modal.ts, src/css/component-styles.css, src/influxmeas/influxmeascfg.component.ts, src/influxmeas/influxmeaseditor.html, src/influxserver/influxservercfg.component.ts, src/influxserver/influxservereditor.html, src/measfilter/measfiltercfg.component.ts, src/measfilter/measfiltereditor.html, src/measgroup/measgroupcfg.component.ts, src/measgroup/measgroupeditor.html, src/oidcondition/oidconditioncfg.component.ts, src/oidcondition/oidconditioneditor.html, src/snmpdevice/snmpdevicecfg.component.ts, src/snmpdevice/snmpdevicecfg.service.ts, src/snmpdevice/snmpdeviceeditor.html, src/snmpmetric/snmpmetriccfg.component.ts, src/snmpmetric/snmpmetriceditor.html
- Add forms validators on all fields, fixed or dynamic ones. Fix #139 
- The hidden values on forms are not sent. Fix #139
- Now the control validation message always visible.
- Changed behaviour when the field set  are changed on Measurement Fields form. Fix #142
- Normalised field names according to interface structures.
=> UI Add forms validators on all fields, fixed and dynamic ones

pkg/config/database.go
=> Add checks for non-existing items on byID API call

pkg/config/database.go, pkg/config/sqlconfig.go, src/common/test-connection-modal.ts, src/customfilter/customfilter.service.ts, src/customfilter/customfiltercfg.component.ts, src/customfilter/test-filter-modal.ts, src/customfilter/testingfilter.html, src/measgroup/measgroupcfg.component.ts, src/snmpdevice/snmpdevicecfg.component.ts
- Implemented Edit for CustomFilter component
- Enhanced control and validators on adding/editing CustomFilter
- Added Related Measement relation on CustomFilter
- Fix checks on ID changes when editing Measurement Group
- Fix static backdrop on Test/Filter Modal to guarantee correct unsubscribe of pending API request
=> UI Implemented Edit function on CustomFilters and minor fixes

src/common/dataservice/export-file-modal.ts, src/common/dataservice/export.service.ts, src/common/dataservice/import-file-modal.ts, src/common/dataservice/import-modal-styles.css, src/common/dataservice/treeview.ts, src/home/home.html, src/home/home.ts
- Added new Bulk Export feature
This new component extends already existing Export component allowing the user select multiple wanted objects to be exported:
**Access:**
The new feature will be accessible from Data Management menu.
**Component functionality**
The user can select if want to do a Recursive Export selecting it:
=> UI Add Bulk Export feature

conf/example_config.sql, src/common/dataservice/export-file-modal.ts, src/customfilter/test-filter-modal.ts, src/snmpdevice/snmpdevicecfg.component.ts
- Fix error when creating `Measurement Filter` from `Custom Filter` add/eddit form
- Fix field `v3privprot` that was showing on `AuthNoPriv`
- Fix `example_config.sql` with the newest changes on DB since last change
- Fix single export that wasn't looking on `Recursive` field
=> UI Minor fixes

pkg/agent/output/influx.go, pkg/webui/webserver.go, src/influxserver/influxservercfg.component.ts, src/influxserver/influxservercfg.service.ts, src/influxserver/influxservereditor.html
- Added InfluxDB test connection button to know if server is up. Fixes #82 
The button will be shown when editing/adding a new InfluxDB Server.
=> UI added Test Connection on InfluxDB Servers, fixes #82

src/common/dataservice/export-file-modal.ts, src/common/test-connection-modal.ts, src/customfilter/test-filter-modal.ts, src/customfilter/testingfilter.html, src/runtime/runtime.component.ts, src/runtime/runtimeview.html
- Added filter on OID queries results. Now the user is able to filter by values. It is added on:
* CustomFilter add/edit and
* Test Connection from devices add/edit forms.
- Improve snmpdevice filter list on Runtime component
- Added spinner when "SendQuery" is getting data on Test Connection component
=> UI Add and improved search filters on OID query results, runtime devices list and bulk export

src/common/validation.service.ts, src/influxserver/influxservereditor.html, src/snmpdevice/snmpdeviceeditor.html
Quick change to make all password fields (that I've found) of type `password`
=> Password fields shouldn't display the actual password

src/snmpdevice/snmpdevicecfg.component.ts, src/snmpdevice/snmpdeviceeditor.html
- Fixed 'null' string on ExtraTags when the user tries to add a new Device and doesn't touch/modify the field. Fixes #173 
- Small typos fixes
=> UI Fixed 'null' string on ExtraTags when add a new Device without modifying/touching the field, fixes #173

src/common/custom-directives.ts, src/influxserver/influxservereditor.html, src/main.module.ts, src/snmpdevice/snmpdeviceeditor.html
- Added new toggle button to allow the user show/hide password fields when it is clicked on InfluxDB component and SNMPDevice component.
=> UI Added new toggle button to show/hide password fields

src/common/dataservice/export-file-modal.ts, src/common/dataservice/treeview.ts
- Added new key selector on Bulk Export filter. This option enables the user to filter by a single property on all components:
- Added found values with key selector to clarify what item is going to export.
- Added buttons to Select/Deselect items. _NOTE:_ This will remove/add current filter results.
- Added button to Clear All selected items.
- Added role buttons on icons.
- Changed button icons to make them more intuitive:
=> 	UI Add Key selector on Bulk Export filter, add Select/Deselect All items, add Clear All on already selected items

src/common/validation.service.ts, src/snmpdevice/snmpdevicecfg.component.ts
- Fixed web UI exception when importing snmpdevice without extra-tag field improving frontend validations. Fixes #186
=> UI Fix web exception when importing snmpdevice without extra-tags field, fixes #186

pkg/config/measurementcfg.go, pkg/config/snmpmetriccfg.go, pkg/config/sqlconfig.go
Improved API validators on :
- Metrics
- Measurement
- Measurement Group
- Influx Server
- Measurement Filters
- OID Conditions
- Custom Filters
=> Improve API validators on components

src/common/httpAPI.ts
- Fix encoded URLs. This will allow to set/get components parameters with blank spaces at the end. Fixes #168
=> UI Fix encoded URLS, fixes  #168

src/app/app.html, src/css/simple-sidebar.css, src/home/about-modal.ts, src/home/home.css, src/home/home.html, src/home/home.service.ts, src/home/home.ts, src/home/index.ts, src/main.module.ts
- Added collapse property to menu. The user can show/hide the menu  with the "hamburger" button on top navbar.
- Moved navbar to top with collapse button, about button and help button.
- Improved styles and menu descriptions.
- Added `About` button that shows basic and release info of SNMPCollector
- Added `Help` button which sends to the SNMPCollector Wiki.
- Split home services functions to a new file, according with the other components
- Fixed the case when a 403 is returned, the home component was loading in async mode until it process the response.
- Fixed blank spaces when the user uses different zoom than 100%. Now the width of each component must fills all the screen.
=> UI Home Refactor

src/common/global-constants.ts, src/customfilter/customfiltercfg.component.ts, src/customfilter/customfiltereditor.html, src/influxmeas/influxmeascfg.component.ts, src/influxmeas/influxmeaseditor.html, src/influxserver/influxservercfg.component.ts, src/influxserver/influxservereditor.html, src/measfilter/measfiltercfg.component.ts, src/measfilter/measfiltereditor.html, src/measgroup/measgroupcfg.component.ts, src/measgroup/measgroupeditor.html, src/oidcondition/oidconditioncfg.component.ts, src/oidcondition/oidconditioneditor.html, src/runtime/runtime.component.ts, src/runtime/runtimeview.html, src/snmpdevice/snmpdevicecfg.component.ts, src/snmpdevice/snmpdeviceeditor.html, src/snmpmetric/snmpmetriccfg.component.ts, src/snmpmetric/snmpmetriceditor.html
- Added more selectors for instances with several devices
- Added "All" selector to display all components on tables
=> UI Improve ItemsPerPage

src/common/ng-table/components/table/ng-table.component.ts, src/common/table-actions.ts, src/main.module.ts, src/snmpdevice/snmpdevicecfg.component.ts, src/snmpdevice/snmpdeviceeditor.html
- Added new action on tables. This fiirst PR implements new actions on SNMPDevices component tables,  allowing the user to edit several items at once. The available options are Remove and ChangeOption.
- Set `Community` field type as password with show directive.
=> UI Add action on SNMP Devices component tables

src/common/ng-table/components/table/ng-table.component.ts
This PR removes the unnecessary getData function on tables. This function could cause some problems when the row has some key with a dot.
=> UI Removed getData function on tables

src/common/multiselect-dropdown.ts, src/common/table-actions.ts, src/common/table-available-actions.ts, src/snmpdevice/snmpdevicecfg.component.ts, src/snmpdevice/snmpdeviceeditor.html
- Added `ExtraTags` option on available table actions
- Added new option to available actions: `AppendProperty`. This option allows the user to append some property. This is available for `MeasurementGroups`, `MeasurementFilters` and `ExtraTags`.
- Added `CheckAll` and `Uncheck All` options on multiselect selectors
- Added validators on `Input` type options when `AppendProperty` or `ChangeProperty` option is selected.
- Minor style fix on `Enable/Disable` edit button
- Exported list of available options to another file in order to reduce component code
- Cleaned code and prepared to be implemented in other components
=> UI Enhance Table Options with new action on MeasFilters, MeasGroups and Extradata

src/common/multiselect-dropdown.ts, src/snmpdevice/snmpdeviceeditor.html
- Enhances style of multiselects with colors, icons and show the number of results
- Changed the behaviour of `Check all` button. Now only the filtered results are selected with the button: `Check all filtered`
- Readded export button on snmp devices table
=> UI Improve Multiselect filtering and checks options

src/common/table-available-actions.ts, src/snmpdevice/snmpdevicecfg.component.ts, src/snmpmetric/snmpmetriccfg.component.ts, src/snmpmetric/snmpmetriceditor.html
- Added Table Actions on SNMPMetrics. This will allow the user to Remove several items at once and change some properties
- Added default items per page as 20
=> UI Add Table actions on SNMPMetric components

src/common/custom-pipe-module.ts, src/common/ng-table/components/ng-table-module.ts, src/common/ng-table/components/table/ng-table.component.ts, src/main.module.ts, src/runtime/runtime.component.ts, src/runtime/runtime.service.ts, src/runtime/runtimeview.html
First attempt to refactor Runtime component
- Added list on runtime snmpdevices list
- Added button options to enable/disable devices
- Added button to reset snmp connections
- Added button to open the test connection console
=> UI Add tables on runtime devices list

src/common/ng-table/components/table/ng-table.component.ts, src/runtime/runtime.component.ts, src/runtime/runtimeview.html
This PR tries to enhance style new Runtime component with:
- Added spinner when loading for the first time the detailed view of a device
- Swapped buttons colors of SetActive, now is more intuitive
- Separates action buttons of device
- Added colors on Report icons
=> UI Enhanced tables on Runtime component

src/common/ng-table/components/table/ng-table.component.ts, src/runtime/runtime.component.ts, src/runtime/runtimeview.html
- Added icon to show if entire row is valid to be sent to Influx
- Added icon to show if there is no data on a measurement, it also applies when filter results are 0
- The back button is visible when trying to recieve the info. The user can back to `List` mode without reloading Runtime component 
- Added `Active/Deactived` labels to show the user the state of the devices
- Fixed exception when click on table cells
- Fixed columns sorting when swapping from different views
- Fixed Refresh button on `View` mode which was reloading all visual components and losing visual scope
- Removed residual/unused code
=> UI Add validation icons on Rutime metric table & small fixes

src/common/table-available-actions.ts, src/customfilter/customfiltercfg.component.ts, src/customfilter/customfiltereditor.html, src/influxmeas/influxmeascfg.component.ts, src/influxmeas/influxmeaseditor.html, src/influxserver/influxservercfg.component.ts, src/influxserver/influxservereditor.html, src/measfilter/measfiltercfg.component.ts, src/measfilter/measfiltereditor.html, src/measgroup/measgroupcfg.component.ts, src/measgroup/measgroupeditor.html, src/oidcondition/oidconditioncfg.component.ts, src/oidcondition/oidconditioneditor.html
- Added available table actions on all components and finishes with the feature of granting the user the chance to edit/remove some items at once.
- Normalized component styles
- Set up 20 items per page on all components
=> UI Add Table available actions on all components

src/common/table-available-actions.ts
- Added UpdateFltFreq as an available table action to allow the user do mass changes over devices. Fix for #272
=> UI Add Filter Freq field on device available table actions

src/common/ng-table/components/table/ng-table.component.ts
- Added tooltip description on icon next to indexes to show the user if the measurement is valid or not
- Hide null values on metric tooltip in order to do not show incorrect information to the user
- Minor enhancement on index column tooltip.
=> UI Enhanced tooltip on runtime metric tables

src/common/table-available-actions.ts, src/varcatalog/varcatalogeditor.html
- Added "Remove" in new Var Catalog available actions
=> UI Added Remove as an available table actions on new VarCatalog component

src/snmpdevice/snmpdevicecfg.component.ts, src/snmpdevice/snmpdeviceeditor.html
- Added selectors and inputs on Device Vars.  This PR enhances the field Device Vars in order to avoid set up non-existent variables on Variable Catalogue component. This field allows the user to override default values for specific devices
=> UI Add selectors on Device Vars field

src/runtime/runtimeview.html, src/snmpdevice/snmpdevicecfg.component.ts
- Added override catalog vars at runtime device detail.
- Added missed code when updating a snmpdevice and changed the var catalog
=> UI Added override catalog vars on SNMPDevice detail and added missing code

src/core/http.service.ts, src/core/loader/loader.component.html
- Added redirect to login and show message if the server is stopped
=> UI Added redirect to login and show message if the server is stopped

src/css/component-styles.css, src/influxmeas/influxmeaseditor.html, src/influxserver/influxservereditor.html, src/measfilter/measfiltereditor.html, src/measgroup/measgroupeditor.html, src/oidcondition/oidconditioneditor.html, src/snmpdevice/snmpdeviceeditor.html, src/snmpmetric/snmpmetriceditor.html, src/varcatalog/varcatalogeditor.html
- Split components add/edit forms into  different sections. This change will help the user to know what is configuring
- Created new buttons style
- Set up scroll into form to do not loose form buttons scope:
=> UI Split components add/edit forms into different sections, enhanced styles

src/customfilter/test-filter-modal.ts, src/influxserver/influxservercfg.component.ts
- Fixed OK alerts on ping Devices and InfluxServers from Filter and InfluxDB components
=> UI Removed alert on ping call

CHANGELOG.md, pkg/agent/device/snmpdevice.go, pkg/agent/device/stats.go, pkg/data/utils/utils.go, src/runtime/runtime.component.ts, src/runtime/runtimeview.html, src/snmpdevice/snmpdevicecfg.component.ts, src/snmpdevice/snmpdeviceeditor.html
=> cicle -> cycle, pooling -> polling

src/common/ng-table/components/table/ng-table.component.ts, src/common/ng-table/components/table/ng-table.html, src/snmpdevice/snmpdevicecfg.component.ts, src/snmpdevice/snmpdeviceeditor.html
- Added `Test Connection` button on snmp devices table. Now the user is allowed to test connection without editing the device or checking it at runtime
=> UI Added test connection button on snmp devices table

src/app/app.routes.ts, src/common/spinner.ts, src/core/http.service.ts, src/core/loader/loader.component.html, src/home/home.ts, src/login/login.html, src/runtime/runtimeview.html
- Changed `/login` URL to `/sign-in` due to possible API collision call
- Added message to runtime spinner in order to clarify the wait time on detailed runtime info
- Fix for #312 . Removed alert if response status code 403
=> UI Changed /login to /sign-in, added info message on runtime spinner and fix #312

pkg/agent/device/measgather.go, pkg/data/measurement/measurement.go, pkg/data/measurement/metrictable.go
- Fix Fix for gathering metrics from eval metrics based on oidconditionevals
=> Fix for gathering metrics from eval metrics based on oidconditionevals

src/common/dataservice/export-file-modal.ts, src/common/table-available-actions.ts, src/snmpdevice/snmpdevicecfg.component.ts, src/snmpdevice/snmpdevicecfg.data.ts, src/snmpdevice/snmpdeviceeditor.html, src/snmpmetric/snmpmetriccfg.data.ts, src/snmpmetric/snmpmetriceditor.html
- Fix slug name mismatch when trying to export SNMPDevices. Not it is normalized with backend code
=> UI Fix slug name mismatch when trying to export snmpdevices, now its normalized with backend code

pkg/config/snmpmetriccfg.go
=> Add support for whitespace, dash and underscore in BITS and ENUM arrays

pkg/config/dbconfig.go, src/common/validation.service.ts, src/snmpdevice/snmpdevicecfg.component.ts
=> Forbid invalid FQDN hosts

pkg/agent/agent.go
This PR adds or rewords the code comments in agent.go to make them more godoc compliant.
It is a WiP, more commits will follow as I dig further into the code. 
-- vma
[This work is sponsored by [Kosc Telecom](http://www.kosc-telecom.fr/en/home/)]
=> Improvement: refactor code comments

pkg/data/measurement/influxpoint.go, pkg/data/measurement/measurement.go, pkg/data/metric/snmpmetric.go
- Fix #410 - Added extra validations when setting timestamp
- Fix #409 - Fix parameters generation on value/indexed cases
=> Fix wrong params and timestamps on InfluxDB points. Fixes #410, #409

pkg/data/filter/oidfilter.go, pkg/data/snmp/snmp.go
Fixes #433. It would best to see the issue for the full details.
=> Extended PduVal2Str() so that more PDUs can handled as strings

CHANGELOG.md, pkg/config/measurementcfg.go, pkg/data/measurement/measurement_test.go, pkg/mock/README.md, pkg/mock/snmpserver.go, pkg/mock/snmpserver_test.go
A very basic Snmp Mock Server to build measurement unit tests , which need for a snmpd backend to get , transform and format data.
=> added snmp mock server  and some measurement unit tests

CHANGELOG.md, pkg/data/metric/snmpmetric.go, pkg/data/metric/snmpmetric_test.go, src/common/validation.service.ts, src/snmpmetric/snmpmetriccfg.component.ts, src/snmpmetric/snmpmetriceditor.html
added trimming options on OctetString metrics
fixes #405
=> added trimming options on OctecString metrics

CHANGELOG.md, pkg/agent/agent.go, pkg/data/filter/filefilter.go, pkg/webui/apicfg-impexp.go, pkg/webui/apicfg-snmpdevice.go
- changed version on changelog to 0.9.0
- fixed some logging format
=> added changelog and fixed some logs formats

pkg/data/measurement/formatindextag.go
=> added MAC transformation option to the Format Index tag , fix #463 

pkg/agent/device/snmpdevice.go, pkg/config/dbconfig.go, pkg/data/measurement/measurement.go, pkg/data/measurement/measurement_test.go, pkg/data/snmp/client.go, pkg/data/snmp/snmp.go, pkg/mock/snmpserver.go, src/snmpdevice/snmpdevicecfg.component.ts, src/snmpdevice/snmpdevicecfg.data.ts, src/snmpdevice/snmpdevicecfg.service.ts, src/snmpdevice/snmpdeviceeditor.html
default set to 60 , close #378
=> snmp client refactor, added MaxOids for limit Get Requests on certain devices

CHANGELOG.md, pkg/webui/websession.go
This fix prevents for API blocking requests , improves user experience on working with the frontend and also prevents automation processes blocking user interaction.
=> fixed blocking API requests
