toni-moreno/snmpcollector

package.json
Lock ng2-bootstrap to version 1.1.13 to avoid broken UI
=> Lock ng2-bootstrap to 1.1.13

pkg/webcontext.go, pkg/webserver.go, pkg/websession.go, public/app/app.routes.ts, public/home/home.ts, public/login/login.ts
Now only logged in people can access to the snmpcollector API.
This is a requirement to add online runtime control like , agent restart, and device runtime activation/deactivation , etc.
=> added security to the snmpcollector API

public/influxmeas/influxmeascfg.component.ts, public/influxmeas/influxmeascfg.service.ts, public/influxmeas/influxmeaseditor.html
This allows the user select if the metric on a defined measurement is sent or not.
The agent will collect the value but it won't be sent on InfluxDB server. It is really useful on new metrics defined as eval type.
=> Add report metric field option on add and edit measurements forms

pkg/model.go, pkg/webserver.go
returning code when bad username/password, showing meas_id instead of measgroups_id when deleting a measurement
=> Minor fixes

public/measgroup/measgroupcfg.component.ts, public/snmpdevice/snmpdevicecfg.component.ts
The component was throwing exception when initiating the multiselect if selectable options weren't loaded before its init.
=> Fix occasional filter exception when init multiselect template

src/runtime/runtime.component.ts, src/runtime/runtimeview.html
- Fix reset measurement index when selecting other device. Seems selected measurement index was not reset when other device is selected.
- Added tooltip info on measurement buttons with metric related title
=> UI Fix reset measurement index when selecting other device on runtime view

src/common/test-connection-modal.ts, src/snmpdevice/snmpdevicecfg.component.ts, src/snmpdevice/snmpdeviceeditor.html
Seems it was an error that on sending the ping of testconnection it was using the default value of community (public). Now the show function is passing the updated form from the main component
=> UI Fix test connection modal values on snmping using form values

src/app/app.routes.ts, src/app/app.ts, src/common/blockui/blockui-component.ts, src/common/blockui/blockui-service.ts, src/common/blockui/blockui.css, src/common/test-connection-modal.ts, src/home/home.html, src/home/home.ts, src/main.module.ts
- Added UI Blocker, applied when the user clicks on reload-conf button.
It will appear a spinner
-  Added better description of reload conf:
When reload conf  finishes, the elapsed time and the last reload appears on tooltip/icon on reload config button
- Fixed routes
Now the user is not redirected to login when setting home or base href, instead, it reloads to /home.
=> UI Add ui-blocker component, fix routes

src/common/test-connection-modal.ts, src/influxmeas/influxmeascfg.service.ts
- Added single select on test connection modal
- Split measurements on indexed and inderect indexed
- Correctly unsubscribe controlling hide buttons
- Added OID condition instead of deprecated filters condOID
- Now all the selectable values are loaded only when the user select  its parent, it instead of loading all of them on the initialisation of the component
=> UI Add singleselect on Test Connection Modal, minor fixes and enhancements

src/common/multiselect-dropdown.ts, src/measfilter/measfiltercfg.component.ts, src/measfilter/measfiltereditor.html, src/snmpmetric/snmpmetriceditor.html
Seems we didn't check if the user changes some dependant fields witht the same form name, as the metric datasource type or metric type.
When the user changes between those fields, the value remained on the formname. Now it resets unless they are loaded from edit or new with previous data.
=> UI Fix refresh value when changing between field types with the same form name

pkg/config/database.go, pkg/webui/webserver.go, src/customfilter/test-filter-modal.ts, src/customfilter/testingfilter.html
Seems we missed some changes on DB relation when unified the filter names on the single  filter_name  field. This PR fixes:
- Custom filter binds correctly to the measurement filter
- Custom fiilter are deleted correctly from the relational components (measurement filters)
- OIDCond are deleted correctly from the relational components (measurement filters, metric with condeval)
=> UI Fix DB relation update when deleting a customfilter or oidcondition on relational components

src/common/multiselect-dropdown.ts, src/css/component-styles.css, src/home/home.html
- The border fits on selector height
- The selectors zindex are correctly over the footer:
=> UI Enhanced styles on multiselect, fixed zindex on selects with footer navbar

src/snmpmetric/snmpmetriccfg.component.ts
It seems that we missed BaseOID field when DataSrcType is STRINGPARSER
=> UI Fix base OID hidden field when DataSrcType is STRINGPARSER

src/common/dataservice/import-file-modal.ts
- Fixed enabled import button when the users unselect from dialog box. #177 
- Small style fixes for selectors
- Disable Overwrite/Autorename buttons if there is some of them at true.
=> UI Fix enabled import button when the users unselect from dialog, fixes #177

src/runtime/runtimeview.html
- Fix hidden runtime options if the device is not connected. This PR allows the user to change rt options even the device is not connected. Fixes #182
=> UI Fix hide runtime options if the device is not connected, fixes #182

pkg/agent/device/snmpdevice.go, pkg/agent/device/stats.go, src/common/ng-table/components/table/ng-table.component.ts, src/runtime/runtime.component.ts, src/runtime/runtime.service.ts, src/runtime/runtimeview.html
- Add new columns on `Runtime` table - `TagMap` and `SysDesc`. This will allow the user to make accurate filter of configured devices to see its behaviour 
- Add `Test Connection` button  on device runtime view
=> UI Add  TagMap and SysDesc as new columns on runtime table

src/runtime/runtime.component.ts
Small fix for no bind action when runtime tables reset button was clicked. This PR fixes #247
=> UI Fix runtime tables reset button, fixes #247

pkg/data/snmp/snmp.go
- Fix #254 adding a new validation to skip SystemOIDs when the field is set as [null] by XORM engine
=> Fix unable to test connection on runtime tables due to null SystemOIDs

src/customfilter/test-filter-modal.ts, src/snmpdevice/snmpdeviceeditor.html
- Fix on SNMPDevice when DeviceTagValue was set with host, the UI was sending a request with value "name" instead of "host", so it was skipped by the SNMPCollector and was sending the tag with the `ID`
- Fix on CustomFilter modal when trying to create another field after cancelling a Filter Creation. It didn't reset the var so the modal was stuck on the frontend
=> UI - Minor fixes on SNMPDevice DeviceTagValue and CustomFilter - filter creation modal

src/common/dataservice/import-file-modal.ts
- Replaced event.srcElement for event.target due to FF incompatibility. This PR fixes #258
=> UI Replace event.srcElement for event.target due to FF incompatibility 

CHANGELOG.md, src/runtime/runtime.component.ts, src/runtime/runtimeview.html
- Added filters by status on Runtime device table. This PR allows the user to filter the devices by `Actived`, `Deactived` and `Active but not connected`. Fixes #260 
Notes:
- In order to improve the filtering, the existing filter (input normal text) will be applied taking into account the new status filters
- The `Active but not connected` filter will only appear when some device meet the given condition.
=> UI Add filters by status on Runtime device table

src/influxmeas/influxmeaseditor.html, src/influxserver/influxservereditor.html, src/measfilter/measfiltereditor.html, src/measgroup/measgroupeditor.html, src/oidcondition/oidconditioneditor.html, src/runtime/runtime.component.ts, src/snmpdevice/snmpdevicecfg.component.ts, src/snmpdevice/snmpdeviceeditor.html, src/snmpmetric/snmpmetriceditor.html
- Simplified create and modify templates on all components. This PR removes duplicated code on HTML so it simplifies coding over it
- Fix on new runtime filter button which was not filtering by not actived devices
- Small fix on Measurement Filters, the field EnableAlias was duplicated when the FilterType was set up with "file"
- Small fix on SNMPDevice community field. It was set up as a Static Field which was causing confusion when SNMPVersion v3 was selected
=> UI Simplified create and modify templates in one on all components

src/common/ng-table/components/table/ng-table.component.ts, src/runtime/runtime.component.ts
- Added TagKey on runtime metric column title. It changes the hardcoded `Index` column title by the real TagKey set up on measurement configuration. This column will only appear now on indexed measurements
=> UI Added TagKey on runtime metric column title

src/common/ng-table/components/table/ng-table.component.ts, src/common/ng-table/components/table/ng-table.html
- Fix tooltip exception on RuntimeTables icons. Seems that we missed a blank space on `container="body"` property. This PR normalizes values and the property is set up without `""`
- Renamed html according to other ng-tables components
=> UI Fix Runtime tooltip on tables component, renamed html

src/influxmeas/influxmeaseditor.html
- Fixed exception `No provider for TemplateRef!` on measurements fields dropdown. The directive changed on the last version of ngx-bootrstrap modue using caret `*`
=> UI Fix on measurement field dropdown

src/common/multiselect-dropdown.ts, src/snmpdevice/snmpdevicecfg.component.ts, src/snmpdevice/snmpdevicecfg.service.ts
- Fixed blank var inserted on DB when no `DeviceVar` was selected on form.
- Split multiselect `id` and `name` option properties when is defined with single-select option
=> UI Fixed blank device vars inserted on DB, minor enhancements on multiselect dropdown to split id and name properties for options

src/common/test-connection-modal.ts
- Added unsubcribe on OID queries when hiding test connection modal
- Added spinner in the first OID query
- Added role button on `+` from history panel
=> UI Fixed unsubscribe when hiding test connection modal on OID queries

pkg/config/measurementcfg.go
- Fixed unable to add a measurement with a STRINGEVAL field with a formula containing CONDITIONEVAL fields
=> Fix unable to add a measurement with eval fields within oid conditon on extradata

pkg/config/snmpmetriccfg.go, pkg/data/metric/snmpmetric.go, src/common/table-available-actions.ts, src/snmpmetric/snmpmetriccfg.component.ts, src/snmpmetric/snmpmetriceditor.html
Sometimes we need to replace numbers with some text. For example, ifType is better read as `ethernetCsmacd(6)` istead of `6`.
ENUM is used like BIT STRING, but instead of checking bit values, it checks for the number.
With ifType we can now make new metric, for example, `ifType-switch`, then set `isTag` to `True`, `Base OID` to `.1.3.6.1.2.1.2.2.1.3` and `ExtraData` to `ethernetCsmacd(6) mpls(166) other(1) propVirtual(53) softwareLoopback(24)`. And as a result we have a nice readable tag instead of number.
=> Add ENUM Cooked Metric Type

pkg/data/metric/snmpmetric.go
Fixes #329, ENUM returned raw value as int64 when there was no match for index in ENUM list.
=> ENUM should always return a string

pkg/webui/apicfg-snmpdevice.go, src/common/blockui/blockui-service.ts, src/common/blockui/blockui.css, src/common/ng-table/components/table/ng-table.html, src/common/table-list.component.ts, src/home/home.html, src/runtime/runtime.data.ts, src/snmpdevice/snmpdevicecfg.component.ts, src/snmpdevice/snmpdevicecfg.data.ts, src/snmpdevice/snmpdevicecfg.service.ts, src/snmpdevice/snmpdeviceeditor.html
Added runtime operations on device configuration. This PR extends to the user to the available actions from device configurations to change runtime without reload config. This PR implements #349 
It has been implemented adding a new column on list and a button when edit/creating:
* List
* New/Edit
On the following table are described the new available ops:
Mode | Action | Available from | Description
-- | -- | -- | --
full | Add | Add/Edit device   forms | Allows to add a   device in configuration and deploy it on runtime
full | Update | Add/Edit device form | Allows to update   device in config and runtime
full | Delete | Devices list | Allows to do a full   delete of device  in runtime and   configuration
runtime | Deploy/undeploy | Devices list | Allows to  deploy/undeploy a device in …
=> Add new runtime operations from device config

CHANGELOG.md, README.md, pkg/config/snmpmetriccfg.go, pkg/data/metric/snmpmetric.go, pkg/data/snmp/snmp.go, pkg/webui/apicfg-snmpmetric.go, src/snmpmetric/snmpmetriccfg.component.ts, src/snmpmetric/snmpmetriccfg.service.ts, src/snmpmetric/snmpmetriceditor.html
Until 0.7.6 Snmpcollector send data to its influxDB backend only as floating point numbers ( except on MULTI STRING PARSER where you can choose the final type for each part) 
Now with this PR snmpcollector will have ability to make type some kind of data conversion once the data has been gathered /  computed , for all types ( depending of course on the datasource type)
=> Add conversion to snmpmetric

pkg/agent/agent.go
When no device is found, the mutex is currently not released .
=> Bugfix: release mutex even on premature return.

CHANGELOG.md, pkg/agent/device/snmpdevice.go, pkg/config/measurementcfg.go, pkg/data/measurement/formatmultiindex.go, pkg/data/measurement/influxpoint.go, pkg/data/measurement/measurement.go, pkg/data/measurement/measurement_test.go, pkg/data/measurement/metrictable.go, src/common/generic-modal.ts, src/common/multiselect-dropdown.ts, src/common/ng-table/components/table/ng-table.component.ts, src/common/ng-table/components/table/ng-table.html, src/common/test-connection-modal.ts, src/common/validation.service.ts, src/css/component-styles.css, src/influxmeas/influxmeascfg.component.ts, src/influxmeas/influxmeascfg.data.ts, src/influxmeas/influxmeascfg.service.ts, src/influxmeas/influxmeaseditor.html, src/measfilter/measfiltercfg.component.ts, src/measfilter/measfiltereditor.html, src/runtime/runtime.component.ts, src/runtime/runtimeview.html
SNMPCollector only allowed basic measurements: direct and indirect
index. It covered almost all the cases, but some complicated MIBs like
Cisco QoS were not possible to be retrieved
This PR adds new measurement types based on GetMode property to allow to
retrieve metrics from complicated MIBs like QoS
- Indexed with multi indirect TAG:
Allow to define multiple TagOIDs with custom index comparison in order
to irerate over different SNMP tables
- Multi Index:
Alows to define multiple indexes with a dependency system to heridate
tags and build a custom index to be used by measurement metrics
=> Added Multi Index and Indexed with multi indirect tag measurements

go.mod, go.sum, pkg/data/measurement/measurement.go, pkg/data/snmp/snmp.go, pkg/mock/snmpserver_test.go
After the release of gosnmp v.1.28 they reverted the behaviour of octetstring, back to []byte instead of string.
This PR reverts also the changes and fixes gosnmp to the last commit (1.28.1)
=> Revert octetstring string cast due to revert on core gosnmp lib after 1.28 release

CHANGELOG.md, package.json, pkg/data/measurement/measurement_test.go, pkg/data/metric/snmpmetric.go
When using MULTISTRINGPARSER metric type, if the used capture group was
empty, it will generate a field with `key=value -->  key=`.
The format is invalid on InfluxDB and data was not being sent
This PR adds a simple check that if the value is null, the field will be
ommited on the output
=> Fix invalid field error on MULTISTRINGPARSER with void capture group

CHANGELOG.md, pkg/webui/apirt-agent.go
In order to accelerate the reconfiguration option ( reloadconf sometimes tooks too much  , at least as many time as the slowest device ) sometimes could be minutes... and this enables the ability to force process shutdown from api, but we need external tools to restart.
Could be a good option if running snmpcollector as docker-image with the ` --restart=always` option. or another kind of supervisor tool like "supervisord".
This option acts as a  fast workaround
=> Feature/add shutdown rt  api option

CHANGELOG.md, pkg/agent/device/snmpdevice.go, pkg/agent/device/stats.go, pkg/agent/selfmon/selfmon.go, pkg/data/measurement/influxpoint.go, pkg/data/metric/snmpmetric.go
now from grafana we will be able to  query % of devices actives/connected with 1 query queries over device stats.
```
select sum(last_c)*100/sum(last_a) as percent_active from   (select last(connected_value) as last_c, last(active_value) as last_a from selfmon_device_stats where instance='dev-toni' and device_active = 'true' and time > now() - 10m group by device)
time                 percent_active
----                 --------------
1970-01-01T00:00:00Z 100
```
or with absolute numbers.
```
select sum(last_c) as connected , sum(last_a) as active from   (select last(connected_value) as last_c, last(active_value) as last_a from selfmon_device_stats where instance='dev-toni' and device_active = 'true' and time > now() - 10m group by device)
time                 connected active
---- …
```
=> added active_value,connected_value fields and device_active,device_conected tags in order to improve device statistics

CHANGELOG.md, pkg/data/measurement/measurement.go, pkg/data/stats/gatherstats.go, src/runtime/runtimeview.html
PR to fix #514  and UI runtime view when the device is not connected
Detail:
- Remove ResetStats call to delegate into the upper function in order to control and manage stats behaviour. Fixes https://github.com/toni-moreno/snmpcollector/issues/514
- Change the agg on device filter_duration overall stats to use the max instead of the sum of times
- Fix UI runtime device detail when the device is not connected
=> Fix #514 , filter_duration stats

CHANGELOG.md, package.json, pkg/data/measurement/measurement.go
On the measurement gatherloop the measurement is marked as non-connected if it becomes unresponsive or the metrica cannot be retrieved for some connectivity reason.
When it happens, the gatherloop tries to reconnect again querying complete sysinfo and resets the snmpclient
This PR tries to fix the logic of the snmpclient inherit from the measurement, as it is using a pointer of a copy instead of the original snmpclient.
In this case, any change on the measurement snmpclient doesn't populates to the multiindex measurement snmpclient, and an already closed connection was being used and the load index is not being done and all the indexes were remain as the last time that they got gethered (wrong if the processed failed at some point)
fix #524
=> fix: fix already closed connections on multiindex measurements
